[{"name": "test.test_split_date_continues.SplitDateContinues.test_calls", "status": "passed", "message": "", "passed": true, "points": ["p05-01.1"], "backtrace": []}, {"name": "test.test_split_date_continues.SplitDateContinues.test_columns", "status": "failed", "message": "\nArrays are not equal\nFirst six column names were incorrect!\nMismatch: 100%\n x: array(['Auroransilta', 'Eteläesplanadi', 'Huopalahti (asema)',\n       'Kaisaniemi/Eläintarhanlahti', 'Kaivokatu', 'Kulosaaren silta et.'],\n      dtype=object)\n y: array(['Weekday', 'Day', 'Month', 'Year', 'Hour', 'Auroransilta'],\n      dtype='<U12')", "passed": false, "points": ["p05-01.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"C:\\Users\\koske\\Documents\\Koodit\\hy-data-analysis-with-python-summer-2019\\part05-e01_split_date_continues\\test\\test_split_date_continues.py\", line 33, in test_columns\n    err_msg=\"First six column names were incorrect!\")\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\testing\\_private\\utils.py\", line 904, in assert_array_equal\n    verbose=verbose, header='Arrays are not equal')\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\testing\\_private\\utils.py\", line 827, in assert_array_compare\n    raise AssertionError(msg)\n"]}, {"name": "test.test_split_date_continues.SplitDateContinues.test_content", "status": "passed", "message": "", "passed": true, "points": ["p05-01.1"], "backtrace": []}, {"name": "test.test_split_date_continues.SplitDateContinues.test_dtypes", "status": "failed", "message": "\nArrays are not equal\nIncorrect column types in first six columns!\nMismatch: 83.3%\n x: array([dtype('float64'), dtype('float64'), dtype('float64'),\n       dtype('float64'), dtype('float64'), dtype('float64')], dtype=object)\n y: array([<class 'object'>, <class 'int'>, <class 'int'>, <class 'int'>,\n       <class 'int'>, <class 'float'>], dtype=object)", "passed": false, "points": ["p05-01.1"], "backtrace": ["  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\unittest\\case.py\", line 615, in run\n    testMethod()\n", "  File \"C:\\Users\\koske\\Documents\\Koodit\\hy-data-analysis-with-python-summer-2019\\part05-e01_split_date_continues\\test\\test_split_date_continues.py\", line 38, in test_dtypes\n    err_msg=\"Incorrect column types in first six columns!\")\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\testing\\_private\\utils.py\", line 904, in assert_array_equal\n    verbose=verbose, header='Arrays are not equal')\n", "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\testing\\_private\\utils.py\", line 827, in assert_array_compare\n    raise AssertionError(msg)\n"]}, {"name": "test.test_split_date_continues.SplitDateContinues.test_shape", "status": "passed", "message": "", "passed": true, "points": ["p05-01.1"], "backtrace": []}]